CREATE TABLE IF NOT EXISTS P_LOAN_APPLICATION (
    APP_ID SERIAL PRIMARY KEY,
    SERIOUS_DLQ_2 INT NOT NULL,
    REVOLVING_UTILIZATION FLOAT NOT NULL,
    AGE INT NOT NULL,
    PAST_DUE_DAYS_30_59 INT,
    DEBT_RATIO FLOAT NOT NULL,
    MONTHLY_INCOME FLOAT,
    OPEN_CREDIT_LINES_AND_LOANS INT NOT NULL,
    PLUS_DAYS_LATE_90 INT NOT NULL,
    REAL_ESTATE_LOANS_OR_LINES INT NOT NULL,
    PAST_DUE_DAYS_60_89 INT,
    NUMBER_OF_DEPENDENTS FLOAT,
    CREATED_TS TIMESTAMP NOT NULL
);
